spring.application.name=PRODUCT-SERVICE
server.port=8026

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Credit?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Hibernate DDL Auto (create/update tables)
spring.jpa.hibernate.ddl-auto=update

# Enable SQL Logging (good for development, not for production)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Cloud Config Client (if needed)
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=true

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888
welcome.message=Bienvenue dans le service produit !
management.endpoints.web.exposure.include=refresh