spring.application.name=Contract-Service
server.port=8024

#eureka register
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

##################### H2 ########################
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=Maroua
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/CantratDB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = create
#####################################################
########MAIL CONFIGURATION##########
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=kassem.benhenda@esprit.tn
spring.mail.password=wllpycbrshhckhbn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
logging.level.org.springframework.scheduling=DEBUG
#Config Client properties
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=true
