    spring.application.name=Credit-Service
    server.port=8028

    #eureka register
    eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
spring.servlet.multipart.enabled=true
# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Credit?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=selmimaher12@gmail.com
spring.mail.password=ejhm wrsr kllk mzcn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true









    #Config Client properties
    spring.cloud.config.import-check.enabled=false
    spring.cloud.config.fail-fast=true
