spring.application.name=UserService
server.port=8023
#eureka register

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
spring.data.mongodb.uri=mongodb://localhost:27017/test


logging.level.org.springframework.security=DEBUG

#Config Client properties

spring.cloud.config.import-check.enabled=false

spring.cloud.config.fail-fast=true